[build]
  # Build command for the web app
  command = "cd apps/web && npm install --legacy-peer-deps && npm run build"
  
  # Publish directory (where the built files are)
  publish = "apps/web/dist"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build settings
  NPM_FLAGS = "--production=false"
  
  # Exclude unused environment variables from secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_MESHY_API_KEY"

# Auto-deploy settings
[build.processing]
  skip_processing = false

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"